version: 2.1

parameters:
  api_jobs_tags:
    default: "^api.+$"
    description: Trigger job steps if tag matches, otherwise skip steps
    type: string
  ui_jobs_tags:
    default: "^ui.+$"
    description: Trigger job steps if tag matches, otherwise skip steps
    type: string
    
jobs:
  api_job_1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - when:
          condition:
            matches: { pattern: <<pipeline.parameters.api_jobs_tags>>, value: << pipeline.git.tag >> }
          steps:
            - run: echo "Hellow World from api_job_1"
  api_job_2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - when: 
          condition:
            matches: { pattern: <<pipeline.parameters.api_jobs_tags>>, value: << pipeline.git.tag >> }
          steps:
            - checkout
            - run: echo "Hellow World from api_job_2"
        
  ui_job_1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - when:
          condition:
            matches: { pattern: <<pipeline.parameters.ui_jobs_tags>>, value: << pipeline.git.tag >> }
          steps:
            - checkout
            - run: echo "Hellow World from ui_job_1"
  ui_job_2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - when:
          condition:
            matches: { pattern: <<pipeline.parameters.ui_jobs_tags>>, value: << pipeline.git.tag >> }
          steps:
            - checkout
            - run: echo "Hellow World from ui_job_2"
workflows:
  test-workflow:
    jobs:
      - api_job_1
      - api_job_2
      - ui_job_1
      - ui_job_2
